[package]
name = "RustyDSA"
version = "0.1.1"
authors = ["mefreanzy"]
edition = "2018"
description = "A libary for Rust data structure."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
